### ISSUE TITLE
Incompatible with channels 3

### ISSUE THREAD

**Issue by OmarWKH** [czue/celery-progress#68] opened 2020-11-17 13:51 UTC
Related to #56.

Websocket breaks when channels 3 is installed. Channels 2.4.0 works.

**Comment by EJH2** [comment] 2020-12-12 09:15
Websocket breaking in channels v3 seems to stem from [this issue](https://github.com/django/channels/issues/1552#issuecomment-720099469). This can be fixed by adding the websocket url in routing.py as such:
```py
urlpatterns = [
    url(r'^ws/progress/(?P<task_id>[\w-]+)/?$', consumers.ProgressConsumer.as_asgi()),
]
```
Now, either we can do that and drop support for channels v2, or do a try/except clause and support both. Thoughts @czue @OmarWKH?

**Comment by czue** [comment] 2020-12-13 12:10
I guess if there's no major downside and it's a simple try/catch then supporting both for now seems better?

**Comment by Hapyr** [comment] 2020-12-17 12:20
i'm a little confused by the incopatiblities....
I have the same error that was mentioned above. 
I am using generic consumer and the routings and have actually adapted all the changes from the release notes. Except the block to "channels.middleware.BaseMiddleware". Can this be the reason. What is meant here?

**Comment by EJH2** [comment] 2020-12-17 22:46
Are you encountering this issue as a result of using this library, or just channels in general? I haven't been able to reproduce this issue since the change

**Comment by Hapyr** [comment] 2020-12-18 12:23
> Are you encountering this issue as a result of using this library, or just channels in general? I haven't been able to reproduce this issue since the change

i do not use this lib. it is a bug/bug in channels.
I have also already moved my comment to the channels issue page. Feel free to delete it here.

**Closed** 2021-01-11 07:56 UTC
